server:
  port: 15500


spring:
  application:
    name: SEARCH-SERVICE
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
  #  batch:
  #    job:
  #      enabled: false
  servlet:
    multipart:
      max-file-size: 51200KB
      max-request-size: 51200KB

springdoc:
  swagger-ui:
    path: /swagger-ui.html




